{
  user(login: "{USER}") {
    pinnedItems(first: 6, types: REPOSITORY) {
      totalCount
      edges {
        node {
          ... on Repository {
            name
            stargazers {
              totalCount
            }
            watchers {
              totalCount
            }
            forks {
              totalCount
            }
            homepageUrl
            url
          }
        }
      }
    }
  }
}